language: node_js
node_js:
- '5'
before_install:
- git config user.name "Travis CI" && git config user.email "$COMMIT_AUTHOR_EMAIL"
- openssl aes-256-cbc -K $encrypted_8a1f9e29c905_key -iv $encrypted_8a1f9e29c905_iv
  -in travis_konference_id_rsa.enc -out travis_konference_id_rsa -d
- chmod 600 travis_konference_id_rsa
- eval `ssh-agent -s`
- ssh-add travis_konference_id_rsa
- git config user.name "Travis CI"
- git config user.email "travis@foobar.com"
- rvm install 2.3.0
before_script: "./s.sh"
script: "./p.sh"
